// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"snowgo/internal/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysDictItem(db *gorm.DB, opts ...gen.DOOption) sysDictItem {
	_sysDictItem := sysDictItem{}

	_sysDictItem.sysDictItemDo.UseDB(db, opts...)
	_sysDictItem.sysDictItemDo.UseModel(&model.SysDictItem{})

	tableName := _sysDictItem.sysDictItemDo.TableName()
	_sysDictItem.ALL = field.NewAsterisk(tableName)
	_sysDictItem.ID = field.NewInt32(tableName, "id")
	_sysDictItem.DictID = field.NewInt32(tableName, "dict_id")
	_sysDictItem.DictCode = field.NewString(tableName, "dict_code")
	_sysDictItem.ItemName = field.NewString(tableName, "item_name")
	_sysDictItem.ItemCode = field.NewString(tableName, "item_code")
	_sysDictItem.Status = field.NewString(tableName, "status")
	_sysDictItem.SortOrder = field.NewInt32(tableName, "sort_order")
	_sysDictItem.Description = field.NewString(tableName, "description")
	_sysDictItem.CreatedAt = field.NewTime(tableName, "created_at")
	_sysDictItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_sysDictItem.fillFieldMap()

	return _sysDictItem
}

type sysDictItem struct {
	sysDictItemDo sysDictItemDo

	ALL         field.Asterisk
	ID          field.Int32
	DictID      field.Int32  // 字典ID
	DictCode    field.String // 字典编码
	ItemName    field.String // 枚举显示名称
	ItemCode    field.String // 枚举值编码
	Status      field.String // 状态：Active 启用，Disabled 禁用
	SortOrder   field.Int32  // 排序号
	Description field.String // 描述
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s sysDictItem) Table(newTableName string) *sysDictItem {
	s.sysDictItemDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDictItem) As(alias string) *sysDictItem {
	s.sysDictItemDo.DO = *(s.sysDictItemDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDictItem) updateTableName(table string) *sysDictItem {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.DictID = field.NewInt32(table, "dict_id")
	s.DictCode = field.NewString(table, "dict_code")
	s.ItemName = field.NewString(table, "item_name")
	s.ItemCode = field.NewString(table, "item_code")
	s.Status = field.NewString(table, "status")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.Description = field.NewString(table, "description")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *sysDictItem) WithContext(ctx context.Context) *sysDictItemDo {
	return s.sysDictItemDo.WithContext(ctx)
}

func (s sysDictItem) TableName() string { return s.sysDictItemDo.TableName() }

func (s sysDictItem) Alias() string { return s.sysDictItemDo.Alias() }

func (s sysDictItem) Columns(cols ...field.Expr) gen.Columns { return s.sysDictItemDo.Columns(cols...) }

func (s *sysDictItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDictItem) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["dict_id"] = s.DictID
	s.fieldMap["dict_code"] = s.DictCode
	s.fieldMap["item_name"] = s.ItemName
	s.fieldMap["item_code"] = s.ItemCode
	s.fieldMap["status"] = s.Status
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["description"] = s.Description
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s sysDictItem) clone(db *gorm.DB) sysDictItem {
	s.sysDictItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDictItem) replaceDB(db *gorm.DB) sysDictItem {
	s.sysDictItemDo.ReplaceDB(db)
	return s
}

type sysDictItemDo struct{ gen.DO }

func (s sysDictItemDo) Debug() *sysDictItemDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDictItemDo) WithContext(ctx context.Context) *sysDictItemDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDictItemDo) ReadDB() *sysDictItemDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDictItemDo) WriteDB() *sysDictItemDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDictItemDo) Session(config *gorm.Session) *sysDictItemDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDictItemDo) Clauses(conds ...clause.Expression) *sysDictItemDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDictItemDo) Returning(value interface{}, columns ...string) *sysDictItemDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDictItemDo) Not(conds ...gen.Condition) *sysDictItemDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDictItemDo) Or(conds ...gen.Condition) *sysDictItemDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDictItemDo) Select(conds ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDictItemDo) Where(conds ...gen.Condition) *sysDictItemDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDictItemDo) Order(conds ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDictItemDo) Distinct(cols ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDictItemDo) Omit(cols ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDictItemDo) Join(table schema.Tabler, on ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDictItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDictItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDictItemDo) Group(cols ...field.Expr) *sysDictItemDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDictItemDo) Having(conds ...gen.Condition) *sysDictItemDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDictItemDo) Limit(limit int) *sysDictItemDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDictItemDo) Offset(offset int) *sysDictItemDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDictItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysDictItemDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDictItemDo) Unscoped() *sysDictItemDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDictItemDo) Create(values ...*model.SysDictItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDictItemDo) CreateInBatches(values []*model.SysDictItem, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDictItemDo) Save(values ...*model.SysDictItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDictItemDo) First() (*model.SysDictItem, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictItem), nil
	}
}

func (s sysDictItemDo) Take() (*model.SysDictItem, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictItem), nil
	}
}

func (s sysDictItemDo) Last() (*model.SysDictItem, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictItem), nil
	}
}

func (s sysDictItemDo) Find() ([]*model.SysDictItem, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysDictItem), err
}

func (s sysDictItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDictItem, err error) {
	buf := make([]*model.SysDictItem, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDictItemDo) FindInBatches(result *[]*model.SysDictItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDictItemDo) Attrs(attrs ...field.AssignExpr) *sysDictItemDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDictItemDo) Assign(attrs ...field.AssignExpr) *sysDictItemDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDictItemDo) Joins(fields ...field.RelationField) *sysDictItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDictItemDo) Preload(fields ...field.RelationField) *sysDictItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDictItemDo) FirstOrInit() (*model.SysDictItem, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictItem), nil
	}
}

func (s sysDictItemDo) FirstOrCreate() (*model.SysDictItem, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictItem), nil
	}
}

func (s sysDictItemDo) FindByPage(offset int, limit int) (result []*model.SysDictItem, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDictItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDictItemDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDictItemDo) Delete(models ...*model.SysDictItem) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDictItemDo) withDO(do gen.Dao) *sysDictItemDo {
	s.DO = *do.(*gen.DO)
	return s
}
