// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"snowgo/internal/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysLoginLog(db *gorm.DB, opts ...gen.DOOption) sysLoginLog {
	_sysLoginLog := sysLoginLog{}

	_sysLoginLog.sysLoginLogDo.UseDB(db, opts...)
	_sysLoginLog.sysLoginLogDo.UseModel(&model.SysLoginLog{})

	tableName := _sysLoginLog.sysLoginLogDo.TableName()
	_sysLoginLog.ALL = field.NewAsterisk(tableName)
	_sysLoginLog.ID = field.NewInt64(tableName, "id")
	_sysLoginLog.UserID = field.NewInt32(tableName, "user_id")
	_sysLoginLog.Username = field.NewString(tableName, "username")
	_sysLoginLog.IP = field.NewString(tableName, "ip")
	_sysLoginLog.Status = field.NewBool(tableName, "status")
	_sysLoginLog.Message = field.NewString(tableName, "message")
	_sysLoginLog.UserAgent = field.NewString(tableName, "user_agent")
	_sysLoginLog.CreatedAt = field.NewTime(tableName, "created_at")

	_sysLoginLog.fillFieldMap()

	return _sysLoginLog
}

type sysLoginLog struct {
	sysLoginLogDo sysLoginLogDo

	ALL       field.Asterisk
	ID        field.Int64  // 日志主键
	UserID    field.Int32  // 用户 ID
	Username  field.String // 登录用户名
	IP        field.String // 登录 IP
	Status    field.Bool   // 登录状态：1 成功，2 失败
	Message   field.String // 失败原因（成功时为空）
	UserAgent field.String // 浏览器/设备信息
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s sysLoginLog) Table(newTableName string) *sysLoginLog {
	s.sysLoginLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysLoginLog) As(alias string) *sysLoginLog {
	s.sysLoginLogDo.DO = *(s.sysLoginLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysLoginLog) updateTableName(table string) *sysLoginLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.UserID = field.NewInt32(table, "user_id")
	s.Username = field.NewString(table, "username")
	s.IP = field.NewString(table, "ip")
	s.Status = field.NewBool(table, "status")
	s.Message = field.NewString(table, "message")
	s.UserAgent = field.NewString(table, "user_agent")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sysLoginLog) WithContext(ctx context.Context) *sysLoginLogDo {
	return s.sysLoginLogDo.WithContext(ctx)
}

func (s sysLoginLog) TableName() string { return s.sysLoginLogDo.TableName() }

func (s sysLoginLog) Alias() string { return s.sysLoginLogDo.Alias() }

func (s sysLoginLog) Columns(cols ...field.Expr) gen.Columns { return s.sysLoginLogDo.Columns(cols...) }

func (s *sysLoginLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysLoginLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["username"] = s.Username
	s.fieldMap["ip"] = s.IP
	s.fieldMap["status"] = s.Status
	s.fieldMap["message"] = s.Message
	s.fieldMap["user_agent"] = s.UserAgent
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sysLoginLog) clone(db *gorm.DB) sysLoginLog {
	s.sysLoginLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysLoginLog) replaceDB(db *gorm.DB) sysLoginLog {
	s.sysLoginLogDo.ReplaceDB(db)
	return s
}

type sysLoginLogDo struct{ gen.DO }

func (s sysLoginLogDo) Debug() *sysLoginLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysLoginLogDo) WithContext(ctx context.Context) *sysLoginLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysLoginLogDo) ReadDB() *sysLoginLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysLoginLogDo) WriteDB() *sysLoginLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysLoginLogDo) Session(config *gorm.Session) *sysLoginLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysLoginLogDo) Clauses(conds ...clause.Expression) *sysLoginLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysLoginLogDo) Returning(value interface{}, columns ...string) *sysLoginLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysLoginLogDo) Not(conds ...gen.Condition) *sysLoginLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysLoginLogDo) Or(conds ...gen.Condition) *sysLoginLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysLoginLogDo) Select(conds ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysLoginLogDo) Where(conds ...gen.Condition) *sysLoginLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysLoginLogDo) Order(conds ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysLoginLogDo) Distinct(cols ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysLoginLogDo) Omit(cols ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysLoginLogDo) Join(table schema.Tabler, on ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysLoginLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysLoginLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysLoginLogDo) Group(cols ...field.Expr) *sysLoginLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysLoginLogDo) Having(conds ...gen.Condition) *sysLoginLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysLoginLogDo) Limit(limit int) *sysLoginLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysLoginLogDo) Offset(offset int) *sysLoginLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysLoginLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysLoginLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysLoginLogDo) Unscoped() *sysLoginLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysLoginLogDo) Create(values ...*model.SysLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysLoginLogDo) CreateInBatches(values []*model.SysLoginLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysLoginLogDo) Save(values ...*model.SysLoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysLoginLogDo) First() (*model.SysLoginLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) Take() (*model.SysLoginLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) Last() (*model.SysLoginLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) Find() ([]*model.SysLoginLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysLoginLog), err
}

func (s sysLoginLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysLoginLog, err error) {
	buf := make([]*model.SysLoginLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysLoginLogDo) FindInBatches(result *[]*model.SysLoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysLoginLogDo) Attrs(attrs ...field.AssignExpr) *sysLoginLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysLoginLogDo) Assign(attrs ...field.AssignExpr) *sysLoginLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysLoginLogDo) Joins(fields ...field.RelationField) *sysLoginLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysLoginLogDo) Preload(fields ...field.RelationField) *sysLoginLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysLoginLogDo) FirstOrInit() (*model.SysLoginLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) FirstOrCreate() (*model.SysLoginLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysLoginLog), nil
	}
}

func (s sysLoginLogDo) FindByPage(offset int, limit int) (result []*model.SysLoginLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysLoginLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysLoginLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysLoginLogDo) Delete(models ...*model.SysLoginLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysLoginLogDo) withDO(do gen.Dao) *sysLoginLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
