// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"snowgo/internal/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSysOperationLog(db *gorm.DB, opts ...gen.DOOption) sysOperationLog {
	_sysOperationLog := sysOperationLog{}

	_sysOperationLog.sysOperationLogDo.UseDB(db, opts...)
	_sysOperationLog.sysOperationLogDo.UseModel(&model.SysOperationLog{})

	tableName := _sysOperationLog.sysOperationLogDo.TableName()
	_sysOperationLog.ALL = field.NewAsterisk(tableName)
	_sysOperationLog.ID = field.NewInt64(tableName, "id")
	_sysOperationLog.OperatorID = field.NewInt32(tableName, "operator_id")
	_sysOperationLog.OperatorName = field.NewString(tableName, "operator_name")
	_sysOperationLog.OperatorType = field.NewString(tableName, "operator_type")
	_sysOperationLog.Resource = field.NewString(tableName, "resource")
	_sysOperationLog.ResourceID = field.NewInt32(tableName, "resource_id")
	_sysOperationLog.Action = field.NewString(tableName, "action")
	_sysOperationLog.TraceID = field.NewString(tableName, "trace_id")
	_sysOperationLog.BeforeData = field.NewString(tableName, "before_data")
	_sysOperationLog.AfterData = field.NewString(tableName, "after_data")
	_sysOperationLog.Description = field.NewString(tableName, "description")
	_sysOperationLog.IP = field.NewString(tableName, "ip")
	_sysOperationLog.CreatedAt = field.NewTime(tableName, "created_at")

	_sysOperationLog.fillFieldMap()

	return _sysOperationLog
}

type sysOperationLog struct {
	sysOperationLogDo sysOperationLogDo

	ALL          field.Asterisk
	ID           field.Int64  // 日志主键
	OperatorID   field.Int32  // 操作人 ID
	OperatorName field.String // 操作人用户名
	OperatorType field.String // 操作来源类型，如 User/System/Job/Api
	Resource     field.String // 操作资源类型，如 user/role/menu
	ResourceID   field.Int32  // 资源ID，如 user 表的主键 ID
	Action       field.String // 操作类型：Create/Update/Delete，默认 Create
	TraceID      field.String // 链路id
	BeforeData   field.String // 修改前数据快照（仅 update/delete 时填）
	AfterData    field.String // 修改后数据快照（仅 create/update 时填）
	Description  field.String // 描述
	IP           field.String // 客户端 IP
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (s sysOperationLog) Table(newTableName string) *sysOperationLog {
	s.sysOperationLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysOperationLog) As(alias string) *sysOperationLog {
	s.sysOperationLogDo.DO = *(s.sysOperationLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysOperationLog) updateTableName(table string) *sysOperationLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.OperatorID = field.NewInt32(table, "operator_id")
	s.OperatorName = field.NewString(table, "operator_name")
	s.OperatorType = field.NewString(table, "operator_type")
	s.Resource = field.NewString(table, "resource")
	s.ResourceID = field.NewInt32(table, "resource_id")
	s.Action = field.NewString(table, "action")
	s.TraceID = field.NewString(table, "trace_id")
	s.BeforeData = field.NewString(table, "before_data")
	s.AfterData = field.NewString(table, "after_data")
	s.Description = field.NewString(table, "description")
	s.IP = field.NewString(table, "ip")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sysOperationLog) WithContext(ctx context.Context) *sysOperationLogDo {
	return s.sysOperationLogDo.WithContext(ctx)
}

func (s sysOperationLog) TableName() string { return s.sysOperationLogDo.TableName() }

func (s sysOperationLog) Alias() string { return s.sysOperationLogDo.Alias() }

func (s sysOperationLog) Columns(cols ...field.Expr) gen.Columns {
	return s.sysOperationLogDo.Columns(cols...)
}

func (s *sysOperationLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysOperationLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["operator_id"] = s.OperatorID
	s.fieldMap["operator_name"] = s.OperatorName
	s.fieldMap["operator_type"] = s.OperatorType
	s.fieldMap["resource"] = s.Resource
	s.fieldMap["resource_id"] = s.ResourceID
	s.fieldMap["action"] = s.Action
	s.fieldMap["trace_id"] = s.TraceID
	s.fieldMap["before_data"] = s.BeforeData
	s.fieldMap["after_data"] = s.AfterData
	s.fieldMap["description"] = s.Description
	s.fieldMap["ip"] = s.IP
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sysOperationLog) clone(db *gorm.DB) sysOperationLog {
	s.sysOperationLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysOperationLog) replaceDB(db *gorm.DB) sysOperationLog {
	s.sysOperationLogDo.ReplaceDB(db)
	return s
}

type sysOperationLogDo struct{ gen.DO }

func (s sysOperationLogDo) Debug() *sysOperationLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysOperationLogDo) WithContext(ctx context.Context) *sysOperationLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysOperationLogDo) ReadDB() *sysOperationLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysOperationLogDo) WriteDB() *sysOperationLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysOperationLogDo) Session(config *gorm.Session) *sysOperationLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysOperationLogDo) Clauses(conds ...clause.Expression) *sysOperationLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysOperationLogDo) Returning(value interface{}, columns ...string) *sysOperationLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysOperationLogDo) Not(conds ...gen.Condition) *sysOperationLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysOperationLogDo) Or(conds ...gen.Condition) *sysOperationLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysOperationLogDo) Select(conds ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysOperationLogDo) Where(conds ...gen.Condition) *sysOperationLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysOperationLogDo) Order(conds ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysOperationLogDo) Distinct(cols ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysOperationLogDo) Omit(cols ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysOperationLogDo) Join(table schema.Tabler, on ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysOperationLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysOperationLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysOperationLogDo) Group(cols ...field.Expr) *sysOperationLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysOperationLogDo) Having(conds ...gen.Condition) *sysOperationLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysOperationLogDo) Limit(limit int) *sysOperationLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysOperationLogDo) Offset(offset int) *sysOperationLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysOperationLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysOperationLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysOperationLogDo) Unscoped() *sysOperationLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysOperationLogDo) Create(values ...*model.SysOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysOperationLogDo) CreateInBatches(values []*model.SysOperationLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysOperationLogDo) Save(values ...*model.SysOperationLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysOperationLogDo) First() (*model.SysOperationLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) Take() (*model.SysOperationLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) Last() (*model.SysOperationLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) Find() ([]*model.SysOperationLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysOperationLog), err
}

func (s sysOperationLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysOperationLog, err error) {
	buf := make([]*model.SysOperationLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysOperationLogDo) FindInBatches(result *[]*model.SysOperationLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysOperationLogDo) Attrs(attrs ...field.AssignExpr) *sysOperationLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysOperationLogDo) Assign(attrs ...field.AssignExpr) *sysOperationLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysOperationLogDo) Joins(fields ...field.RelationField) *sysOperationLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysOperationLogDo) Preload(fields ...field.RelationField) *sysOperationLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysOperationLogDo) FirstOrInit() (*model.SysOperationLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) FirstOrCreate() (*model.SysOperationLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysOperationLog), nil
	}
}

func (s sysOperationLogDo) FindByPage(offset int, limit int) (result []*model.SysOperationLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysOperationLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysOperationLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysOperationLogDo) Delete(models ...*model.SysOperationLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysOperationLogDo) withDO(do gen.Dao) *sysOperationLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
