// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"snowgo/internal/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSystemDictItem(db *gorm.DB, opts ...gen.DOOption) systemDictItem {
	_systemDictItem := systemDictItem{}

	_systemDictItem.systemDictItemDo.UseDB(db, opts...)
	_systemDictItem.systemDictItemDo.UseModel(&model.SystemDictItem{})

	tableName := _systemDictItem.systemDictItemDo.TableName()
	_systemDictItem.ALL = field.NewAsterisk(tableName)
	_systemDictItem.ID = field.NewInt32(tableName, "id")
	_systemDictItem.DictID = field.NewInt32(tableName, "dict_id")
	_systemDictItem.DictCode = field.NewString(tableName, "dict_code")
	_systemDictItem.ItemName = field.NewString(tableName, "item_name")
	_systemDictItem.ItemCode = field.NewString(tableName, "item_code")
	_systemDictItem.Status = field.NewString(tableName, "status")
	_systemDictItem.SortOrder = field.NewInt32(tableName, "sort_order")
	_systemDictItem.Description = field.NewString(tableName, "description")
	_systemDictItem.CreatedAt = field.NewTime(tableName, "created_at")
	_systemDictItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_systemDictItem.fillFieldMap()

	return _systemDictItem
}

type systemDictItem struct {
	systemDictItemDo systemDictItemDo

	ALL         field.Asterisk
	ID          field.Int32
	DictID      field.Int32  // 字典ID
	DictCode    field.String // 字典编码
	ItemName    field.String // 枚举显示名称
	ItemCode    field.String // 枚举值编码
	Status      field.String // 状态：Active 启用，Disabled 禁用
	SortOrder   field.Int32  // 排序号
	Description field.String // 描述
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s systemDictItem) Table(newTableName string) *systemDictItem {
	s.systemDictItemDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemDictItem) As(alias string) *systemDictItem {
	s.systemDictItemDo.DO = *(s.systemDictItemDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemDictItem) updateTableName(table string) *systemDictItem {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.DictID = field.NewInt32(table, "dict_id")
	s.DictCode = field.NewString(table, "dict_code")
	s.ItemName = field.NewString(table, "item_name")
	s.ItemCode = field.NewString(table, "item_code")
	s.Status = field.NewString(table, "status")
	s.SortOrder = field.NewInt32(table, "sort_order")
	s.Description = field.NewString(table, "description")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *systemDictItem) WithContext(ctx context.Context) *systemDictItemDo {
	return s.systemDictItemDo.WithContext(ctx)
}

func (s systemDictItem) TableName() string { return s.systemDictItemDo.TableName() }

func (s systemDictItem) Alias() string { return s.systemDictItemDo.Alias() }

func (s systemDictItem) Columns(cols ...field.Expr) gen.Columns {
	return s.systemDictItemDo.Columns(cols...)
}

func (s *systemDictItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemDictItem) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["dict_id"] = s.DictID
	s.fieldMap["dict_code"] = s.DictCode
	s.fieldMap["item_name"] = s.ItemName
	s.fieldMap["item_code"] = s.ItemCode
	s.fieldMap["status"] = s.Status
	s.fieldMap["sort_order"] = s.SortOrder
	s.fieldMap["description"] = s.Description
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s systemDictItem) clone(db *gorm.DB) systemDictItem {
	s.systemDictItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemDictItem) replaceDB(db *gorm.DB) systemDictItem {
	s.systemDictItemDo.ReplaceDB(db)
	return s
}

type systemDictItemDo struct{ gen.DO }

func (s systemDictItemDo) Debug() *systemDictItemDo {
	return s.withDO(s.DO.Debug())
}

func (s systemDictItemDo) WithContext(ctx context.Context) *systemDictItemDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemDictItemDo) ReadDB() *systemDictItemDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemDictItemDo) WriteDB() *systemDictItemDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemDictItemDo) Session(config *gorm.Session) *systemDictItemDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemDictItemDo) Clauses(conds ...clause.Expression) *systemDictItemDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemDictItemDo) Returning(value interface{}, columns ...string) *systemDictItemDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemDictItemDo) Not(conds ...gen.Condition) *systemDictItemDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemDictItemDo) Or(conds ...gen.Condition) *systemDictItemDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemDictItemDo) Select(conds ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemDictItemDo) Where(conds ...gen.Condition) *systemDictItemDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemDictItemDo) Order(conds ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemDictItemDo) Distinct(cols ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemDictItemDo) Omit(cols ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemDictItemDo) Join(table schema.Tabler, on ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemDictItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemDictItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemDictItemDo) Group(cols ...field.Expr) *systemDictItemDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemDictItemDo) Having(conds ...gen.Condition) *systemDictItemDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemDictItemDo) Limit(limit int) *systemDictItemDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemDictItemDo) Offset(offset int) *systemDictItemDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemDictItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *systemDictItemDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemDictItemDo) Unscoped() *systemDictItemDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemDictItemDo) Create(values ...*model.SystemDictItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemDictItemDo) CreateInBatches(values []*model.SystemDictItem, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemDictItemDo) Save(values ...*model.SystemDictItem) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemDictItemDo) First() (*model.SystemDictItem, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictItem), nil
	}
}

func (s systemDictItemDo) Take() (*model.SystemDictItem, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictItem), nil
	}
}

func (s systemDictItemDo) Last() (*model.SystemDictItem, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictItem), nil
	}
}

func (s systemDictItemDo) Find() ([]*model.SystemDictItem, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemDictItem), err
}

func (s systemDictItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDictItem, err error) {
	buf := make([]*model.SystemDictItem, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemDictItemDo) FindInBatches(result *[]*model.SystemDictItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemDictItemDo) Attrs(attrs ...field.AssignExpr) *systemDictItemDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemDictItemDo) Assign(attrs ...field.AssignExpr) *systemDictItemDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemDictItemDo) Joins(fields ...field.RelationField) *systemDictItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemDictItemDo) Preload(fields ...field.RelationField) *systemDictItemDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemDictItemDo) FirstOrInit() (*model.SystemDictItem, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictItem), nil
	}
}

func (s systemDictItemDo) FirstOrCreate() (*model.SystemDictItem, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDictItem), nil
	}
}

func (s systemDictItemDo) FindByPage(offset int, limit int) (result []*model.SystemDictItem, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemDictItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemDictItemDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemDictItemDo) Delete(models ...*model.SystemDictItem) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemDictItemDo) withDO(do gen.Dao) *systemDictItemDo {
	s.DO = *do.(*gen.DO)
	return s
}
