// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"snowgo/internal/dal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newSystemDict(db *gorm.DB, opts ...gen.DOOption) systemDict {
	_systemDict := systemDict{}

	_systemDict.systemDictDo.UseDB(db, opts...)
	_systemDict.systemDictDo.UseModel(&model.SystemDict{})

	tableName := _systemDict.systemDictDo.TableName()
	_systemDict.ALL = field.NewAsterisk(tableName)
	_systemDict.ID = field.NewInt32(tableName, "id")
	_systemDict.Code = field.NewString(tableName, "code")
	_systemDict.Name = field.NewString(tableName, "name")
	_systemDict.Description = field.NewString(tableName, "description")
	_systemDict.CreatedAt = field.NewTime(tableName, "created_at")
	_systemDict.UpdatedAt = field.NewTime(tableName, "updated_at")

	_systemDict.fillFieldMap()

	return _systemDict
}

type systemDict struct {
	systemDictDo systemDictDo

	ALL         field.Asterisk
	ID          field.Int32
	Code        field.String // 字典编码
	Name        field.String // 字典名称
	Description field.String // 描述
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s systemDict) Table(newTableName string) *systemDict {
	s.systemDictDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s systemDict) As(alias string) *systemDict {
	s.systemDictDo.DO = *(s.systemDictDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *systemDict) updateTableName(table string) *systemDict {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Code = field.NewString(table, "code")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *systemDict) WithContext(ctx context.Context) *systemDictDo {
	return s.systemDictDo.WithContext(ctx)
}

func (s systemDict) TableName() string { return s.systemDictDo.TableName() }

func (s systemDict) Alias() string { return s.systemDictDo.Alias() }

func (s systemDict) Columns(cols ...field.Expr) gen.Columns { return s.systemDictDo.Columns(cols...) }

func (s *systemDict) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *systemDict) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["code"] = s.Code
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s systemDict) clone(db *gorm.DB) systemDict {
	s.systemDictDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s systemDict) replaceDB(db *gorm.DB) systemDict {
	s.systemDictDo.ReplaceDB(db)
	return s
}

type systemDictDo struct{ gen.DO }

func (s systemDictDo) Debug() *systemDictDo {
	return s.withDO(s.DO.Debug())
}

func (s systemDictDo) WithContext(ctx context.Context) *systemDictDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s systemDictDo) ReadDB() *systemDictDo {
	return s.Clauses(dbresolver.Read)
}

func (s systemDictDo) WriteDB() *systemDictDo {
	return s.Clauses(dbresolver.Write)
}

func (s systemDictDo) Session(config *gorm.Session) *systemDictDo {
	return s.withDO(s.DO.Session(config))
}

func (s systemDictDo) Clauses(conds ...clause.Expression) *systemDictDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s systemDictDo) Returning(value interface{}, columns ...string) *systemDictDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s systemDictDo) Not(conds ...gen.Condition) *systemDictDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s systemDictDo) Or(conds ...gen.Condition) *systemDictDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s systemDictDo) Select(conds ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s systemDictDo) Where(conds ...gen.Condition) *systemDictDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s systemDictDo) Order(conds ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s systemDictDo) Distinct(cols ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s systemDictDo) Omit(cols ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s systemDictDo) Join(table schema.Tabler, on ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s systemDictDo) LeftJoin(table schema.Tabler, on ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s systemDictDo) RightJoin(table schema.Tabler, on ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s systemDictDo) Group(cols ...field.Expr) *systemDictDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s systemDictDo) Having(conds ...gen.Condition) *systemDictDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s systemDictDo) Limit(limit int) *systemDictDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s systemDictDo) Offset(offset int) *systemDictDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s systemDictDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *systemDictDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s systemDictDo) Unscoped() *systemDictDo {
	return s.withDO(s.DO.Unscoped())
}

func (s systemDictDo) Create(values ...*model.SystemDict) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s systemDictDo) CreateInBatches(values []*model.SystemDict, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s systemDictDo) Save(values ...*model.SystemDict) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s systemDictDo) First() (*model.SystemDict, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDict), nil
	}
}

func (s systemDictDo) Take() (*model.SystemDict, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDict), nil
	}
}

func (s systemDictDo) Last() (*model.SystemDict, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDict), nil
	}
}

func (s systemDictDo) Find() ([]*model.SystemDict, error) {
	result, err := s.DO.Find()
	return result.([]*model.SystemDict), err
}

func (s systemDictDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SystemDict, err error) {
	buf := make([]*model.SystemDict, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s systemDictDo) FindInBatches(result *[]*model.SystemDict, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s systemDictDo) Attrs(attrs ...field.AssignExpr) *systemDictDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s systemDictDo) Assign(attrs ...field.AssignExpr) *systemDictDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s systemDictDo) Joins(fields ...field.RelationField) *systemDictDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s systemDictDo) Preload(fields ...field.RelationField) *systemDictDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s systemDictDo) FirstOrInit() (*model.SystemDict, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDict), nil
	}
}

func (s systemDictDo) FirstOrCreate() (*model.SystemDict, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SystemDict), nil
	}
}

func (s systemDictDo) FindByPage(offset int, limit int) (result []*model.SystemDict, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s systemDictDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s systemDictDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s systemDictDo) Delete(models ...*model.SystemDict) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *systemDictDo) withDO(do gen.Dao) *systemDictDo {
	s.DO = *do.(*gen.DO)
	return s
}
