// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysLoginLog = "sys_login_log"

// SysLoginLog 登录日志表
type SysLoginLog struct {
	ID        int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true;comment:日志主键" json:"id"`                          // 日志主键
	UserID    int32      `gorm:"column:user_id;type:int(11);not null;index:idx_user_id,priority:1;comment:用户 ID" json:"user_id"`          // 用户 ID
	Username  string     `gorm:"column:username;type:varchar(64);not null;index:idx_username,priority:1;comment:登录用户名" json:"username"`   // 登录用户名
	IP        string     `gorm:"column:ip;type:varchar(64);not null;comment:登录 IP" json:"ip"`                                             // 登录 IP
	Status    bool       `gorm:"column:status;type:tinyint(1);not null;index:idx_status,priority:1;comment:登录状态：1 成功，2 失败" json:"status"` // 登录状态：1 成功，2 失败
	Message   *string    `gorm:"column:message;type:varchar(255);comment:失败原因（成功时为空）" json:"message"`                                     // 失败原因（成功时为空）
	UserAgent *string    `gorm:"column:user_agent;type:varchar(512);comment:浏览器/设备信息" json:"user_agent"`                                  // 浏览器/设备信息
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime(6);not null;index:idx_created_at,priority:1;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
}

// TableName SysLoginLog's table name
func (*SysLoginLog) TableName() string {
	return TableNameSysLoginLog
}
