// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemDictItem = "system_dict_item"

// SystemDictItem 系统字典枚举值表
type SystemDictItem struct {
	ID          int32      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	DictID      int32      `gorm:"column:dict_id;type:int(11);not null;comment:字典ID" json:"dict_id"`                                              // 字典ID
	DictCode    string     `gorm:"column:dict_code;type:varchar(64);not null;uniqueIndex:uk_dict_item,priority:1;comment:字典编码" json:"dict_code"`  // 字典编码
	ItemName    string     `gorm:"column:item_name;type:varchar(128);not null;comment:枚举显示名称" json:"item_name"`                                   // 枚举显示名称
	ItemCode    string     `gorm:"column:item_code;type:varchar(64);not null;uniqueIndex:uk_dict_item,priority:2;comment:枚举值编码" json:"item_code"` // 枚举值编码
	Status      *string    `gorm:"column:status;type:varchar(20);not null;default:Active;comment:状态：Active 启用，Disabled 禁用" json:"status"`         // 状态：Active 启用，Disabled 禁用
	SortOrder   int32      `gorm:"column:sort_order;type:int(11);not null;comment:排序号" json:"sort_order"`                                         // 排序号
	Description *string    `gorm:"column:description;type:text;comment:描述" json:"description"`                                                    // 描述
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName SystemDictItem's table name
func (*SystemDictItem) TableName() string {
	return TableNameSystemDictItem
}
