// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser 用户表
type SysUser struct {
	ID        int32          `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;type:varchar(64);not null;uniqueIndex:uk_username_deleted,priority:1;comment:登录名，业务唯一" json:"username"`                                                  // 登录名，业务唯一
	Tel       string         `gorm:"column:tel;type:varchar(20);not null;uniqueIndex:uk_tel_deleted,priority:1;comment:手机号码" json:"tel"`                                                                     // 手机号码
	Nickname  *string        `gorm:"column:nickname;type:varchar(60);comment:用户昵称" json:"nickname"`                                                                                                          // 用户昵称
	Password  string         `gorm:"column:password;type:varchar(255);not null;comment:pwd" json:"password"`                                                                                                 // pwd
	Email     *string        `gorm:"column:email;type:varchar(100);comment:邮箱" json:"email"`                                                                                                                 // 邮箱
	Remark    *string        `gorm:"column:remark;type:varchar(500);comment:备注" json:"remark"`                                                                                                               // 备注
	Status    *int8          `gorm:"column:status;type:tinyint(4);not null;index:idx_status,priority:1;default:1;comment:用户状态：1 活跃, 2 禁用登录" json:"status"`                                                   // 用户状态：1 活跃, 2 禁用登录
	CreatedBy *int32         `gorm:"column:created_by;type:int(11);index:idx_created_by,priority:1;comment:创建人 ID" json:"created_by"`                                                                        // 创建人 ID
	UpdatedBy *int32         `gorm:"column:updated_by;type:int(11);comment:更新人 ID" json:"updated_by"`                                                                                                        // 更新人 ID
	IsDeleted bool           `gorm:"column:is_deleted;type:tinyint(1);not null;uniqueIndex:uk_tel_deleted,priority:2;uniqueIndex:uk_username_deleted,priority:2;comment:是否删除：0=未删除，1=已删除" json:"is_deleted"` // 是否删除：0=未删除，1=已删除
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(6);comment:删除时间（NULL=未删除）" json:"deleted_at"`                                                                                            // 删除时间（NULL=未删除）
	CreatedAt *time.Time     `gorm:"column:created_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
