// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSystemDict = "system_dict"

// SystemDict 系统字典表
type SystemDict struct {
	ID          int32      `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Code        string     `gorm:"column:code;type:varchar(64);not null;uniqueIndex:uk_code,priority:1;comment:字典编码" json:"code"` // 字典编码
	Name        string     `gorm:"column:name;type:varchar(128);not null;comment:字典名称" json:"name"`                               // 字典名称
	Description *string    `gorm:"column:description;type:text;comment:描述" json:"description"`                                    // 描述
	CreatedAt   *time.Time `gorm:"column:created_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName SystemDict's table name
func (*SystemDict) TableName() string {
	return TableNameSystemDict
}
