// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int32            `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Username     string           `gorm:"column:username;type:varchar(20);not null;index:idx_username,priority:1" json:"username"`
	Password     string           `gorm:"column:password;type:varchar(64);not null" json:"password"`
	Tel          string           `gorm:"column:tel;type:varchar(20);not null;uniqueIndex:uniq_tel,priority:1" json:"tel"`
	Sex          *string          `gorm:"column:sex;type:char(1);default:M;comment:M表示男，F表示女" json:"sex"` // M表示男，F表示女
	WalletAmount *decimal.Decimal `gorm:"column:wallet_amount;type:decimal(12,2);default:0.00" json:"wallet_amount"`
	IsDelete     *bool            `gorm:"column:is_delete;type:tinyint(1);comment:1表示用户已经被删除，0表示可用" json:"is_delete"` // 1表示用户已经被删除，0表示可用
	CreatedAt    *time.Time       `gorm:"column:created_at;type:datetime(6);default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt    *time.Time       `gorm:"column:updated_at;type:datetime(6);default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
