// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserRole = "user_role"

// UserRole 用户-角色关联表
type UserRole struct {
	ID        int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	UserID    int32      `gorm:"column:user_id;type:int(11);not null;index:idx_user_id,priority:1;comment:用户ID" json:"user_id"` // 用户ID
	RoleID    int32      `gorm:"column:role_id;type:int(11);not null;comment:角色ID" json:"role_id"`                              // 角色ID
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime(6);not null;default:CURRENT_TIMESTAMP(6)" json:"updated_at"`
}

// TableName UserRole's table name
func (*UserRole) TableName() string {
	return TableNameUserRole
}
