version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitor-prometheus
    ports:
      - "19090:9090"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8' # 最大cpu的40%
          memory: 8G # 生产环境建议 8G+
    networks:
      - monitor
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    depends_on: # 添加依赖确保Exporter先启动
      - node_exporter
      - mysql_exporter
      - redis_exporter
      - elasticsearch_exporter

  node_exporter:
    image: prom/node-exporter:latest
    container_name: monitor-node-exporter
    ports:
      - "19100:9100"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
    networks:
      - monitor
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9100" ]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: monitor-grafana
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
      - GF_SECURITY_ADMIN_PASSWORD=zx123  # 设置默认密码
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/plugins:/var/lib/grafana/plugins  # 持久化插件
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mysql_exporter:
    image: prom/mysqld-exporter:latest
    container_name: monitor-mysql-exporter
    ports:
      - "19104:9104"
    command:
      - "--mysqld.username=root:zx.123"
      - "--mysqld.address=192.168.0.106:3306"
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9104" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: monitor-redis-exporter
    ports:
      - "19121:9121"
    environment:
      - REDIS_ADDR=redis://192.168.0.106:6379
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9121" ]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: monitor-elasticsearch-exporter
    ports:
      - "19114:9114"
    command:
      - '--es.uri=http://elastic:zx.123@192.168.0.106:9200'
      - '--es.all'
    restart: always
    networks:
      - monitor
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9114" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  monitor:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET:-172.102.0.0/24}
