[debug-jwt]
    issuer = "test-snow"  # 发布人
    jwtSecret = "Tphd67F7Mi%Aapi5iXsXX5ZRJxZF*6wK"  # jwt加密秘钥
    accessExpirationTime = 60  # 访问token到期时间，单位min
    refreshExpirationTime = 720  # 访问token到期时间，单位min

[production-jwt]
    issuer = "snow"  # 发布人
    jwtSecret = "kc&MhZCK$3Q6KMp5dANfZWFfDDSJF@nf"  # jwt加密秘钥
    accessExpirationTime = 60  # 访问token到期时间，单位min
    refreshExpirationTime = 720  # 刷新token到期时间，单位min
