[debug-mysql]
    name = "测试数据库"
    addr = "127.0.0.1:3306"  # 地址
    user = "root"  # 用户名
    password = "zx.123"  # 密码
    database = "test"  # 数据库名字
    charset = "utf8mb4"
    parseTime = true  # 是否支持把数据库datetime和date类型转换为golang的time.Time类型
    loc = "Local"  # 使用系统本地时区
    tablePre = ""  # 表前缀
    maxIdleConns = 4  # 设置闲置的连接数，默认值为2；推荐 ((核心数 * 2) + 有效磁盘数)
    maxOpenConns = 100  # 设置最大打开的连接数，默认值为0，表示不限制。
    maxLifeTime = 180  # 设置了连接可复用的最大时间。单位min
    printSqlLog = true  # 是否打印具体SQL
    slowSqlTime = 200 # 慢sql阈值 单位ms(在设置printSqlLog=true有用)

[production-mysql]
    name = "生产数据库"
    addr = "127.0.0.1:3306"  # 地址
    user = "test"  # 用户名
    password = "test"  # 密码
    database = "test"  # 数据库名字
    charset = "utf8mb4"
    parseTime = true  # 是否支持把数据库datetime和date类型转换为golang的time.Time类型
    loc = "Local"  # 使用系统本地时区
    tablePre = ""  # 表前缀
    maxIdleConns = 6  # 设置闲置的连接数，默认值为2；推荐 ((核心数 * 2) + 有效磁盘数)
    maxOpenConns = 100  # 设置最大打开的连接数，默认值为0，表示不限制。
    maxLifeTime = 120  # 设置了连接可复用的最大时间。单位min
    printSqlLog = false  # 是否打印SQL
    slowSqlTime = 200 # 慢sql阈值 单位ms(在设置printSqlLog=true有用)
